image:
  file: ./tools/docker_dev/.gitpod.Dockerfile
tasks:
  - init: |
      conda activate scipydev
      python setup.py build_ext --inplace
      conda develop .
      git submodule update --init
      cd doc 
      make html-scipyorg
    command: conda activate scipydev

# exposing ports for sphinx-autobuild 
ports:
  - port: 8000
    onOpen: notify