name: Linux Tests

on:
  push:
    branches:
      - master
      - maintenance/**
  pull_request:
    branches:
      - master
      - maintenance/**

jobs:
  Python-37-dbg:
    name: Python 3.7-dbg
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Configure env vars and python packages
        run: |
          sudo apt install python3.7-dbg python3.7-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev ccache swig libmpc-dev
          free -m
          export PATH=/usr/lib/ccache:$PATH
          ccache --zero-stats
          export CCACHE_COMPRESS=1
          python3.7-dbg --version # just to check
          export NPY_NUM_BUILD_JOBS=2
          uname -a
          df -h
          ulimit -a
          set -e -o pipefail
          mkdir builds
          cd builds
          python3.7-dbg -c 'import sys; print("Python debug build:", hasattr(sys, "gettotalrefcount"))'
          python3.7-dbg -m pip install --upgrade pip setuptools wheel cython pytest pytest-xdist argparse pybind11
          python3.7-dbg -m pip install --upgrade mpmath gmpy2
          python3.7-dbg -m pip install --upgrade numpy
          python3.7-dbg -m pip uninstall -y nose
          ccache -s
          cd ..
      - name: Building SciPy
        run: python3.7-dbg -u runtests.py -g -j2 --build-only
      - name: Testing SciPy
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          python3.7-dbg -u runtests.py -g -j2 -m fast -- -rfEX --durations=10 2>&1 | tee runtests.log
          python3.7-dbg tools/validate_runtests_log.py fast < runtests.log
      - name: Dynamic symbol hiding check on Linux
        if: ${{ github.event_name == 'pull_request' }}
        run: ./tools/check_pyext_symbol_hiding.sh build
